# Generated by Django 6.0.1 on 2026-03-02 17:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('mock_full', 'Full Mock Interview'), ('quick_practice', 'Quick Practice')], default='quick_practice', max_length=50)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Total session duration', null=True)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(blank=True, help_text='Average time per question in seconds', null=True)),
                ('average_clarity_score', models.FloatField(blank=True, null=True)),
                ('average_delivery_score', models.FloatField(blank=True, null=True)),
                ('total_filler_words', models.IntegerField(default=0)),
                ('session_feedback', models.TextField(blank=True, help_text='AI-generated overall session feedback')),
                ('session_score', models.FloatField(blank=True, help_text='Overall session score (0-100)', null=True)),
                ('strengths', models.JSONField(blank=True, default=list, help_text='Identified strengths from this session')),
                ('areas_for_improvement', models.JSONField(blank=True, default=list, help_text='Areas to focus on')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Interview Sessions',
                'db_table': 'interview_sessions',
                'ordering': ['-started_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='unknown', max_length=100)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Learning Events',
                'db_table': 'learning_events',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.TextField(default='general')),
                ('current_level', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mastery Records',
                'db_table': 'mastery',
                'ordering': ['-last_updated'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('concept', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('system_design', 'System Design'), ('coding', 'Coding'), ('theoretical', 'Theoretical')], default='theoretical', help_text='High-level category for filtering', max_length=50)),
                ('sub_category', models.CharField(blank=True, help_text='Specific topic (e.g., "recursion", "leadership", "scalability")', max_length=100)),
                ('ideal_duration_seconds', models.IntegerField(blank=True, help_text='Expected time for a good answer (for interview practice)', null=True)),
                ('evaluation_rubric', models.JSONField(blank=True, default=dict, help_text='Structured criteria for grading (STAR method, technical depth, etc.)')),
                ('bloom_level', models.TextField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['category', 'sub_category'], name='questions_categor_75d63a_idx'), models.Index(fields=['concept', 'bloom_level'], name='questions_concept_c146ad_idx')],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.TextField(blank=True, null=True)),
                ('audio_file_path', models.CharField(blank=True, help_text='Path to recorded audio file (S3, local storage, etc.)', max_length=500, null=True)),
                ('transcription', models.TextField(blank=True, help_text='Auto-transcribed text from audio (Whisper API)')),
                ('response_duration_seconds', models.FloatField(blank=True, help_text='How long user took to answer', null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('interview_session', models.ForeignKey(blank=True, help_text='Interview session this response belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='tutor.interviewsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Responses',
                'db_table': 'responses',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SpacedRepetitionQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_time', models.DateTimeField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('repetition_count', models.IntegerField(default=0)),
                ('last_interval', models.IntegerField(default=1)),
                ('last_quality', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Spaced Repetition Queue',
                'db_table': 'spaced_repetition_queue',
                'ordering': ['review_time'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('daily_goal_progress', models.IntegerField(default=0)),
                ('last_daily_goal_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceDeliveryMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_rate_wpm', models.FloatField(blank=True, help_text='Words per minute (ideal: 120-150)', null=True)),
                ('clarity_score', models.FloatField(blank=True, help_text='Pronunciation clarity (0-100, from speech recognition confidence)', null=True)),
                ('filler_words_count', models.IntegerField(default=0, help_text='Count of um, uh, like, you know, etc.')),
                ('filler_words_list', models.JSONField(blank=True, default=list, help_text='Detected filler words with timestamps')),
                ('tone_analysis', models.JSONField(blank=True, default=dict, help_text='Emotion/tone scores')),
                ('pause_count', models.IntegerField(default=0, help_text='Number of significant pauses (>1 second)')),
                ('average_pause_duration', models.FloatField(blank=True, help_text='Average pause length in seconds', null=True)),
                ('volume_variance', models.FloatField(blank=True, help_text='Variance in volume (monotone vs dynamic)', null=True)),
                ('delivery_feedback', models.TextField(blank=True, help_text='Real-time feedback on delivery quality')),
                ('overall_delivery_score', models.FloatField(blank=True, help_text='Composite score (0-100) for delivery quality', null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_model', models.CharField(blank=True, help_text='Which AI model analyzed this', max_length=100)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_metrics', to='tutor.response')),
            ],
            options={
                'verbose_name_plural': 'Voice Delivery Metrics',
                'db_table': 'voice_delivery_metrics',
                'ordering': ['-analyzed_at'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['user', '-started_at'], name='interview_s_user_id_400033_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mastery',
            unique_together={('user', 'concept')},
        ),
        migrations.AddIndex(
            model_name='spacedrepetitionqueue',
            index=models.Index(fields=['user', 'review_time', 'status'], name='spaced_repe_user_id_bc95a3_idx'),
        ),
        migrations.AddIndex(
            model_name='spacedrepetitionqueue',
            index=models.Index(fields=['user', 'status'], name='spaced_repe_user_id_23b6c3_idx'),
        ),
    ]
