# Generated by Django 6.0.1 on 2026-03-02 18:03

from django.db import migrations,models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('concept', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=50, choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('system_design', 'System Design'), ('coding', 'Coding'), ('theoretical', 'Theoretical')], default='theoretical')),
                ('sub_category', models.CharField(max_length=100, blank=True)),
                ('ideal_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('evaluation_rubric', models.JSONField(default=dict, blank=True)),
                ('bloom_level', models.TextField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=timezone.now)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        )

    ]
