# Generated by Django 6.0.1 on 2026-03-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20260302_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('system_design', 'System Design'), ('coding', 'Coding'), ('theoretical', 'Theoretical')], default='theoretical', help_text='High-level category for filtering', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='evaluation_rubric',
            field=models.JSONField(blank=True, default=dict, help_text='Structured criteria for grading (STAR method, technical depth, etc.)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ideal_duration_seconds',
            field=models.IntegerField(blank=True, help_text='Expected time for a good answer (for interview practice)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='sub_category',
            field=models.CharField(blank=True, help_text='Specific topic (e.g., "recursion", "leadership", "scalability")', max_length=100),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'sub_category'], name='questions_categor_75d63a_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['concept', 'bloom_level'], name='questions_concept_c146ad_idx'),
        ),
    ]
