# Generated by Django 6.0.1 on 2026-03-03 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_alter_question_options_alter_question_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualReviewQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_reviews', to='tutor.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Manual Review Queue',
                'db_table': 'manual_review_queue',
                'managed': True,
                'indexes': [models.Index(fields=['user', '-added_at'], name='manual_revi_user_id_7b7521_idx')],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='SkippedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skipped_at', models.DateTimeField(auto_now_add=True)),
                ('skip_count', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Skipped Questions',
                'db_table': 'skipped_questions',
                'managed': True,
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UserQuestionInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('next_review_due', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.FloatField(default=1.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('wants_manual_review', models.BooleanField(db_index=True, default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Question Interactions',
                'db_table': 'user_question_interactions',
                'managed': True,
                'indexes': [models.Index(fields=['user', 'next_review_due'], name='user_questi_user_id_eb2163_idx'), models.Index(fields=['user', 'wants_manual_review'], name='user_questi_user_id_eddf8b_idx')],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
